project_name: npm-download-spammer

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    main: .
    binary: npm-download-spammer

archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - npm-downloads-increaser.json

nfpms:
  - package_name: npm-download-spammer
    file_name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
    vendor: NPM Download Spammer
    homepage: https://github.com/GlobalArtInc/npm-download-spammer
    maintainer: GlobalArt, Inc <tech@globalart.dev>
    description: NPM Download Counter Increaser Tool
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch
