services:
  npm-download-spammer:
    image: globalartltd/npm-download-spammer
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    environment:
      NPM_PACKAGE_NAME: "your-package-name"
      NPM_NUM_DOWNLOADS: 1000
      NPM_MAX_CONCURRENT_DOWNLOAD: 300
      NPM_DOWNLOAD_TIMEOUT: 3000
    stdin_open: true
    tty: true
